projects:
  default:
    schema: graphql/schema.graphql
    extensions:
      endpoints:
        local: http://localhost:3000/graphql
        default: https://api-next.audiencekit.com/graphql
        prod: https://api.audiencekit.com/graphql
